services:
  collector:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command:
      - collector 
      - -c 
      - /etc/finala/config.yaml
    environment:
      - OVERRIDE_API_ENDPOINT=http://api:8081
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    volumes:
        - ./configuration/collector.yaml:/etc/finala/config.yaml
